version: '2'
services:
    rfbloyality-app:
        image: rfbloyality
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rfbloyality-mysql:3306/rfbloyality?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rfbloyality-mysql:
        extends:
            file: mysql.yml
            service: rfbloyality-mysql
